name: Cypress Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress Tests
        uses: cypress-io/github-action@v4
        env:
          CORS_ALLOWED_ORIGIN: "*"
        with:
          build: npm run build
          start: npm run start
